tasks:
  start: npm start
  test: npm test

files:
  model:
    path: src/models/{**}/{*|className}.js
    related: [view, controller]
  controller:
    path: src/controllers/{**}/{*|className}.js
    related:
      - model
      - view
  test:
    path:
      - src/models/{**}/{*|className}.test.js
      - src/controller/{**}/{*|className}.test.js
    related:
      - model
      - controller
  view:
    path: src/templates/{**}/{*|param}.hbs
    related:
      - model
      - controller
  style:
    path: src/styles/{**}/{*|param}.scss
    related:
      - model
      - controller

